### PR TITLE
Shadowlands Backdrop Compatible

### PR DESCRIPTION
**Pull request by LiangYuxuan**
This is a quick compatible code on Shadowlands backdrop changes. I've tested this on PTR, and it works good.

### CODE REVIEW

**Comment by pwilkowski** [comment]
Have you actually checked this for compatibility with SL? Because I have been developing different solution however yours looks better, but does it fully works?

**Comment by Wutname1** [comment]
Don't you want to mixin both `BackdropTemplateMixin and "BackdropTemplate"`? That tends to be the fix I see most people adding.

**Comment by LiangYuxuan** [comment]
I've search for all backdrop APIs StdUi use in the repo.
* `:SetBackdrop`
  Used in `StdUi:ApplyBackdrop`, `StdUi:ClearBackdrop`, `StdUi:PanelWithTitle`, `:PanelWithTitle` use `:Panel` to create a title panel and called `:SetBackdrop` on it, which called `:ApplyBackdrop` already in `:Panel`.
* `:GetBackdrop`
  No
* `:GetBackdropColor`
  No
* `:SetBackdropColor`
  Used in `StdUi:ApplyBackdrop`, `ColorInputMethods` in `ColorPicker.lua`, but `ColorPicker` uses `:HookHoverBorder` when creating.
* `:GetBackdropBorderColor`
  Used in `StdUi.SetHighlightBorder` (to be the hook function in `:HookHoverBorder`), `StdUi:MarkAsValid` which only accept `EditBox`
* `:SetBackdropBorderColor`
  Used in `StdUi:ApplyBackdrop`, `StdUi:MarkAsValid`, `StdUi.SetHighlightBorder`, `StdUi.ResetHighlightBorder`, which discussed above.

I have to say, it should work for all StdUi widgets (most of them will call `ApplyBackdrop` for setting backdrop), but I don't like the `ColorPicker` part. It's like hack. I would like to add an explicit `Mixin` call in `ColorPicker`'s create function if you don't mind, also one for `StdUi:MarkAsValid` for protection (EditBoxs all have backdrop).

**Comment by LiangYuxuan** [comment]
> Don't you want to mixin both `BackdropTemplateMixin and "BackdropTemplate"`? That tends to be the fix I see most people adding.

`BackdropTemplateMixin and "BackdropTemplate"` means `"BackdropTemplate"` actually, and it should be used when frame created. This PR uses the method more like "on demand", it only `Mixin` the backdrop stuff when needed.

**Comment by LiangYuxuan** [comment]
Updated to add an explicit `Mixin` call in `ColorPicker` and protection in `:MarkAsVaild`.

**Pull request merged**
